#!/usr/bin/python3
def only_diff_elements(set_1, set_2):
    a = []
    for i in set_1:
        if i not in set_2:
            a.append(i)
    for i in set_2:
        if i not in set_1:
            a.append(i)
    return a 
